retail-store:
  db:
    host: localhost
    port: 3306
    name: retailstore_prod
    username: retailstore
    password: retailstore

server:
  port: 5533

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${retail-store.db.host}:${retail-store.db.port}/${retail-store.db.name}?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: ${retail-store.db.username}
    password: ${retail-store.db.password}
    database: mysql
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: none